### ISSUE TITLE
Dataset release schedule

### ISSUE THREAD

**Issue by parkjaewoo0611** [megapose6d/megapose6d#2] opened 2023-01-03 01:56 UTC
Hi, first of all, thank you for sharing your awesome work.

We are looking forward to your dataset.

When may it be public?

**Comment by ylabbe** [comment] 2023-01-03 12:57
Hi and thank you for the interest in our work !
The dataset will be released alongside the code. Please see #1 for more information.
I am closing this is as a duplicate of #1.

**Closed by ylabbe** 2023-01-03 12:57 UTC
